/*
프로그래머스 - 있었는데요 없었습니다
by SY
DATE : 2020.10.08
*/
-- 간단 정답
SELECT A.ANIMAL_ID, a.NAME
FROM ANIMAL_INS as A, ANIMAL_OUTS as B
WHERE A.ANIMAL_ID=B.ANIMAL_ID and A.DATETIME>B.DATETIME
order by A.datetime

-- join 활용
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME 
FROM ANIMAL_INS LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID 
WHERE ANIMAL_INS.DATETIME>ANIMAL_OUTS.DATETIME 
ORDER BY ANIMAL_INS.DATETIME